"""v1.14.0 — inline SVG icon set; v1.19.0 — Lucide everywhere.

User report on the VM actions row: the emoji icons read as a jumble —
some rendered as full-colour images (📸 📝), others as thin glyphs (■ ⚙),
with sizes varying per platform and poor legibility at 16 px. 1.14.0
replaced that row with a hand-drawn monochrome set inheriting
`currentColor`; 1.19.0 generalises the approach to the whole console with
the Lucide set, vendored and regenerated by scripts/gen-icons.py.

These tests pin the contract:
  * icons.js stays theme-aware (currentColor, viewBox 24) and keeps the
    semantic names call sites rely on;
  * no rendered source (templates, JS modules, CSS content:) carries a
    pictograph any more — typographic arrows in prose are allowed;
  * every icon name referenced anywhere exists in the generated table, and
    the table matches the generator's manifest;
  * the Lucide licence ships with the tarball.
"""

import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
WEB = ROOT / "web"
JS = WEB / "static" / "js"
CSS = WEB / "static" / "css" / "style.css"
TEMPLATES = WEB / "templates"
ICONS = (JS / "icons.js").read_text()

# Emoji ranges we do NOT want as action-button icons any more.
EMOJI_RE = re.compile("[\U0001F300-\U0001FAFF☀-➿]")

# Everything pictographic that used to be sprinkled through the UI: emoji,
# dingbats, arrows used as controls, geometric shapes, technical symbols
# (⏳ ⏸ ⏻), enclosed ⓘ, braille drag handle ⠿, regional-indicator flags and
# the variation selector. Typographic arrows → ← ↔ stay allowed in prose.
PICTOGRAPH_RE = re.compile(
    "[\U0001F000-\U0001FAFF"      # emoji blocks
    "\U0001F1E6-\U0001F1FF"       # regional indicators (flags)
    "☀-➿"               # misc symbols + dingbats
    "⬀-⯿"               # misc symbols and arrows (⬆ ⬇ ⬢)
    "■-◿"               # geometric shapes (■ ▶ ▼ ● ○)
    "⌀-⏿"               # misc technical (⏳ ⏱ ⏸ ⏻ ⌜)
    "↑↓↕-⇿"          # arrows used as controls (→ ← ↔ stay typographic)
    "ⓘℹ⠿⊡⟳️]"
)

ICON_REF_RE = re.compile(
    r"Icons\.(?:svg|el|dataUri)\(\s*'([A-Za-z0-9]+)'"
    r"|data-icon=\"([A-Za-z0-9]+)\""
    r"|\bicon:\s*'([A-Za-z0-9]+)'"
)

SHIPPED_SOURCES = sorted(
    [p for p in TEMPLATES.glob("*.html")]
    + [p for p in JS.glob("*.js")]
    + [CSS]
)


def _strip_comments(text: str, suffix: str) -> str:
    """Drop block/line comments so documentation may still mention glyphs."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    if suffix == ".html":
        text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    if suffix == ".js":
        # Whole-line // comments and JSDoc-style ' * ' lines only: an inline
        # '//' inside a URL or string must not swallow real code.
        text = "\n".join(
            "" if re.match(r"\s*(//|\*)", ln) else ln for ln in text.splitlines()
        )
    return text


def _paths_keys() -> set:
    block = ICONS.split("BEGIN GENERATED", 1)[1].split("END GENERATED", 1)[0]
    return set(re.findall(r"^\s{4}([A-Za-z_][A-Za-z0-9_]*):", block, flags=re.M))


def _load_generator():
    spec = importlib.util.spec_from_file_location(
        "gen_icons", ROOT / "scripts" / "gen-icons.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# ---------------------------------------------------------------- 1.14.0

def test_icon_set_is_monochrome_and_theme_aware():
    assert "stroke=\"currentColor\"" in ICONS, (
        "icons must inherit the button colour so one set fits every theme")
    assert "viewBox=\"0 0 24 24\"" in ICONS
    # every action of the VM row has an icon
    for name in ("play", "stop", "snapshot", "migrate", "settings",
                 "console", "notes", "restore", "trash", "restart"):
        assert f"{name}:" in ICONS, f"missing icon: {name}"


def test_vm_actions_row_uses_svg_not_emoji():
    app = (JS / "app.js").read_text()
    cell = app.split("vm-actions-cell", 1)[1].split("</td>", 1)[0]
    assert not EMOJI_RE.search(cell), (
        f"emoji left in the VM actions row: {EMOJI_RE.findall(cell)}")
    assert cell.count("Icons.svg(") >= 6


def test_console_toolbar_uses_the_same_icons():
    js = (JS / "vm-console.js").read_text()
    bar = js.split("vm-console-bar", 1)[1].split("vm-console-screen", 1)[0]
    assert not EMOJI_RE.search(bar), (
        f"emoji left in the console toolbar: {EMOJI_RE.findall(bar)}")
    assert bar.count("Icons.svg(") >= 4


def test_icons_script_loads_before_its_users():
    html = (TEMPLATES / "index.html").read_text()
    assert "/static/js/icons.js" in html
    assert html.index("/static/js/icons.js") < html.index("/static/js/app.js"), (
        "icons.js must load before the modules that call Icons.svg()")


def test_every_referenced_icon_is_defined():
    """`Icons.svg()` returns an empty string for an unknown name, so a typo
    silently produces a button with no glyph. Catch it here instead."""
    defined = set(re.findall(r"^\s{4}(\w+):", ICONS, re.M))
    used = set()
    for js in JS.glob("*.js"):
        used |= set(re.findall(r"Icons\.svg\(\s*'(\w+)'", js.read_text()))
    assert used, "no Icons.svg() call found, the scan is broken"
    assert used <= defined, f"icons used but never drawn: {sorted(used - defined)}"


def test_baremetal_actions_use_svg_not_emoji():
    """v1.19.0 — the bare-metal power/install buttons went through the same
    emoji-to-SVG pass as the VM row."""
    js = (JS / "bmc.js").read_text()
    bar = js.split("bmc-power", 1)[1].split("</div>", 1)[0]
    assert not EMOJI_RE.search(bar), (
        f"emoji left on the bare-metal action bar: {EMOJI_RE.findall(bar)}")
    assert bar.count("Icons.svg(") >= 4


def test_panel_header_keeps_svg_labels_unescaped():
    """A header action can carry an SVG label; escaping it would print
    the raw markup."""
    fp = (JS / "floating-panels.js").read_text()
    assert "<\\/svg>$/.test(a.label" in fp or "svg" in fp.split("data-header-action", 1)[1][:400]


# ---------------------------------------------------------------- 1.19.0

def test_no_pictographs_in_shipped_sources():
    """Every rendered glyph is an SVG now. Comments may still describe the
    old emoji; code and markup may not carry one."""
    offenders = []
    for path in SHIPPED_SOURCES:
        if "vendor" in path.parts:
            continue
        clean = _strip_comments(path.read_text(), path.suffix)
        for lineno, line in enumerate(clean.splitlines(), 1):
            hit = PICTOGRAPH_RE.search(line)
            if hit:
                offenders.append(f"{path.relative_to(ROOT)}:{lineno}: {hit.group(0)!r}")
    assert not offenders, "pictographs left in shipped sources:\n" + "\n".join(offenders)


def test_css_content_has_no_glyphs():
    """Pseudo-element icons go through the generated --icon-* masks."""
    values = re.findall(r"content:\s*'([^']*)'", CSS.read_text())
    bad = [v for v in values if PICTOGRAPH_RE.search(v)]
    assert not bad, f"glyphs in CSS content: {bad}"
    css = CSS.read_text()
    for var in ("--icon-check", "--icon-x", "--icon-sort", "--icon-sort-asc", "--icon-sort-desc"):
        assert f"{var}:" in css, f"missing generated mask {var}"
        assert f"var({var})" in css, f"generated mask {var} is unused"


def test_every_referenced_icon_exists():
    keys = _paths_keys()
    assert len(keys) >= 80
    missing = set()
    for path in SHIPPED_SOURCES:
        if "vendor" in path.parts or path == CSS:
            continue
        for m in ICON_REF_RE.finditer(path.read_text()):
            name = next(g for g in m.groups() if g)
            if name not in keys:
                missing.add(f"{path.name}: {name}")
    assert not missing, f"icon names referenced but not generated: {sorted(missing)}"


def test_manifest_matches_generated_block():
    gen = _load_generator()
    assert set(gen.ICONS) == _paths_keys(), (
        "run scripts/gen-icons.py after editing the manifest")
    assert f"lucide-static {gen.LUCIDE_VERSION}" in ICONS
    assert f"lucide-static {gen.LUCIDE_VERSION}" in CSS.read_text()
    assert gen.LUCIDE_INTEGRITY.startswith("sha512-")
    for name in gen.CSS_MASKS.values():
        assert name in gen.ICONS


def test_generated_bodies_inherit_stroke_colour():
    """Lucide children must carry no stroke/fill of their own, otherwise
    currentColor would not reach them and the theme switcher breaks."""
    block = ICONS.split("BEGIN GENERATED", 1)[1].split("END GENERATED", 1)[0]
    assert "stroke=" not in block
    # a few Lucide glyphs carry a solid dot; it must still follow the text colour
    assert not set(re.findall(r'fill="([^"]*)"', block)) - {"currentColor", "none"}


def test_lucide_licence_is_vendored():
    vendor = WEB / "static" / "vendor" / "lucide"
    licence = (vendor / "LICENSE").read_text()
    assert "ISC License" in licence
    readme = (vendor / "README.md").read_text()
    gen = _load_generator()
    assert gen.LUCIDE_VERSION in readme
    assert gen.LUCIDE_INTEGRITY in readme
    header = ICONS.split("const Icons", 1)[0]
    assert "Lucide" in header and "ISC" in header


def test_icons_api_surface():
    exported = ICONS.split("return {", 1)[1].split("}", 1)[0]
    for fn in ("svg", "el", "dataUri", "mount", "has", "names"):
        assert re.search(rf"\b{fn}\b", exported), f"Icons.{fn} not exported"
    assert "data-icon-mounted" in ICONS, "mount() must be idempotent"


def test_templates_mount_their_icons():
    index = (TEMPLATES / "index.html").read_text()
    review = (TEMPLATES / "review.html").read_text()
    assert index.count('data-icon="') >= 30
    assert (JS / "app.js").read_text().count("Icons.mount()") == 1
    assert "/static/js/icons.js" in review and "Icons.mount()" in review


def test_i18n_strings_carry_no_icons():
    """Icons live in sibling elements: applyTranslations() overwrites the
    textContent of translated nodes, which would wipe an inline SVG."""
    src = (JS / "i18n.js").read_text()
    for key in ("overview.tabMetrics", "overview.tabCluster", "overview.tabNetwork",
                "overview.tabStorage", "topology.searchPlaceholder",
                "action.cancelled", "topology.lockedHint"):
        values = re.findall(rf"'{re.escape(key)}':\s*'([^']*)'", src)
        assert len(values) == 5, f"{key} should be defined in the 5 dictionaries"
        for v in values:
            assert not PICTOGRAPH_RE.search(v), f"{key}: {v!r}"
    # the overview sub-tabs put their icon in a sibling span
    index = (TEMPLATES / "index.html").read_text()
    for key, icon in (("overview.tabMetrics", "metrics"), ("overview.tabCluster", "node"),
                      ("overview.tabNetwork", "network"), ("overview.tabStorage", "storage")):
        assert f'data-icon="{icon}"></span> <span data-i18n="{key}"' in index


def test_floating_panel_renders_icon_option():
    fp = (JS / "floating-panels.js").read_text()
    assert fp.count("floating-panel-icon") >= 2, (
        "header and minimised chip must both render opts.icon")
    assert "opts.icon" in fp and "p.opts.icon" in fp


def test_topology_canvas_uses_data_uri_icons():
    src = (JS / "topology.js").read_text()
    assert "'background-image': 'data(icon)'" in src
    for name in ("node", "vm", "volume", "cdrom", "switch", "bundle", "paused"):
        assert f"nodeIcon('{name}')" in src, f"canvas icon {name} missing"
